[package]
name = "ts"
version = "0.1.0"
edition = "2021"

[dependencies]
macros = { path = "../macros" }

[dev-dependencies]
pretty_assertions = "1.4.1"

# todo: put this block in workspace Cargo.toml
[lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"
module_name_repetitions = "allow"
